spring.application.name=product-catalog-api

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:productdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate (automatically creates tables from Entity classes and drops them when app stops.)
spring.jpa.hibernate.ddl-auto=create-drop

# Prints SQL in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
